const data ={
    product : (
        {
            name: 'Stuff Shirt',
            categorry : 'Shirts',
            image : '/image/shirt1.jpg',
            price: 70,
            brand:'Nike',
            rating: 4.5,
            numReview : 10,
            countInStock : 20,
            description : 'A popular shirt',
        }, {
            name: 'Steddy Shirt ',
            categorry : 'Shirts',
            image : '/image/shirt2.jpg',
            price: 60,
            brand:'Adidas',
            rating: 4.2,
            numReview : 10,
            countInStock : 20,
            description : 'A popular shirt',
        }, {
            name: 'JustLove Shirt',
            categorry : 'Shirts',
            image : '/image/shirt3.jpg',
            price: 57,
            brand:'Puma',
            rating: 4.7,
            numReview : 10,
            countInStock : 20,
            description : 'A popular shirt',
        }, {
            name: 'classique Pants',
            categorry : 'Pants',
            image : '/image/Pants1.jpg',
            price: 100,
            brand:'Nike',
            rating: 4.5,
            numReview : 10,
            countInStock : 20,
            description : 'A popular pants',
        }, {
            name: 'Sports Pants',
            categorry : 'Pants',
            image : '/image/pants2.jpg',
            price: 40,
            brand:'Nike',
            rating: 4.2,
            numReview : 10,
            countInStock : 20,
            description : 'A popular pants',
        }, {
            name: 'Swim Shorts',
            categorry : 'Pants',
            image : '/image/Pants3.jpg',
            price: 30,
            brand:'Reebok ',
            rating: 4.8,
            numReview : 10,
            countInStock : 20,
            description : 'A popular Shorts',
        }
    )
}